apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  namespace: ns-nginx
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Welcome to Nginx!</title>
    </head>
    <body>
        <h1>Hello from Nginx!</h1>
        <p>If you see this page, the nginx web server is successfully installed.</p>
    </body>
    </html>