apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ns-nginx
  name: nginx-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nginx-rolebinding
  namespace: ns-nginx
subjects:
- kind: ServiceAccount
  name: default
  namespace: ns-nginx
roleRef:
  kind: Role
  name: nginx-role
  apiGroup: rbac.authorization.k8s.io