apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-statefulset
  namespace: ns-nginx
spec:
  serviceName: "nginx"
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: copy-index-html
        image: deepika2897/nginx:${IMAGE_TAG}
        command: ['sh', '-c', 'cp /usr/share/nginx/html/index.html /mnt/html/index.html']
        volumeMounts:
        - name: nginx-pvc
          mountPath: /mnt/html
      containers:
      - name: nginx
        image: deepika2897/nginx:${IMAGE_TAG}
        ports:
        - containerPort: 443
          name: https
        volumeMounts:
        - name: nginx-pvc
          mountPath: /usr/share/nginx/html
        - name: tls-cert
          mountPath: /etc/ssl/certs
          readOnly: true
        - name: tls-key
          mountPath: /etc/ssl/private
          readOnly: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 443
            scheme: HTTPS
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 443
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: tls-cert
        secret:
          secretName: nginx-tls
          defaultMode: 0400
          items:
          - key: tls.crt
            path: cision.crt
      - name: tls-key
        secret:
          secretName: nginx-tls
          defaultMode: 0400
          items:
          - key: tls.key
            path: cision.key
  volumeClaimTemplates:
  - metadata:
      name: nginx-pvc
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi