name: Deploy Nginx

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./nginx-project
          file: ./nginx-project/Dockerfile
          push: true
          tags: deepika2897/nginx-image:latest

  security-scan:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.29.0
        with:
          image-ref: 'deepika2897/nginx-image:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  deploy-and-test:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Minikube
        uses: medyagh/setup-minikube@latest

      - name: Start Minikube
        run: minikube start --driver=docker

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Create Kubernetes namespace
        run: kubectl apply -f ./nginx-project/namespace.yaml

      - name: Create Kubernetes secret
        run: |
          echo "${{ secrets.SSL_CERT }}" | base64 --decode > /tmp/cision.crt
          echo "${{ secrets.SSL_KEY }}" | base64 --decode > /tmp/cision.key
          kubectl create secret tls nginx-tls \
            --cert=/tmp/cision.crt \
            --key=/tmp/cision.key \
            --namespace=ns-nginx

      - name: Deploy StatefulSet
        run: |
          kubectl apply -f ./nginx-project/nginx-statefulset.yaml
          kubectl rollout status statefulset/nginx-statefulset -n ns-nginx

      - name: Deploy Service
        run: |
          kubectl apply -f ./nginx-project/nginx-service.yaml
          kubectl rollout status service/nginx-service -n ns-nginx

      - name: Port forward and test connection
        run: |
          kubectl port-forward svc/nginx-service 8443:443 -n ns-nginx &
          sleep 10
          curl -k https://localhost:8443
