name: Deploy Nginx

on:
  push:
    branches:
      - main

jobs:
  build-scan-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./nginx-project
          file: ./nginx-project/Dockerfile
          tags: deepika2897/nginx:v1.0.0

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.29.0
        continue-on-error: true
        with:
          image-ref: 'deepika2897/nginx:v1.0.0'
          format: 'table'
          exit-code: '1' 
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'

      - name: Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./nginx-project
          file: ./nginx-project/Dockerfile
          push: true
          tags: deepika2897/nginx:v1.0.0

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Create kubeconfig
        run: |
          mkdir -p ${HOME}/.kube
          echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > ${HOME}/.kube/config
          kubectl config set-context octobay-api --cluster=minikube --namespace=default --user=minikube --kubeconfig=${HOME}/.kube/config
          kubectl config use-context octobay-api --kubeconfig=${HOME}/.kube/config

      - name: Create Kubernetes namespace
        run: kubectl apply -f ./nginx-project/namespace.yaml

      - name: Create Kubernetes secret
        run: |
          echo "${{ secrets.SSL_CERT }}" | base64 --decode > /tmp/cision.crt
          echo "${{ secrets.SSL_KEY }}" | base64 --decode > /tmp/cision.key
          kubectl create secret tls nginx-tls \
            --cert=/tmp/cision.crt \
            --key=/tmp/cision.key \
            --namespace=ns-nginx

      - name: Deploy StatefulSet
        run: |
          kubectl apply -f ./nginx-project/nginx-statefulset.yaml
          kubectl rollout status statefulset/nginx-statefulset -n ns-nginx

      - name: Deploy Service
        run: kubectl apply -f ./nginx-project/nginx-service.yaml

      - name: Port forward and test connection
        run: |
          kubectl port-forward svc/nginx-service 8443:443 -n ns-nginx &
          sleep 10
          curl -k https://localhost:8443